name: Continuous Integration

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: debian-latest

    strategy:
      matrix:
        node-version: [18.x, latest]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install NPM packages
        run: npm ci
      # Ordered from most to least severe/fix order.
      - name: Build project
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Run lint
        run: npm run lint
      - name: Run Typescript checks
        run: npm run tsc
      - name: Run Vue+Typescript checks
        run: npm run vue-tsc
      - name: Run formatting check
        run: npm run formatcheck
